### ISSUE TITLE
Error in "neuralnetwork.ui.js" when switching to any language

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/openroberta-lab#1603]
To reproduce this error open the lab, select any robot/system and select any other language:

![image](https://github.com/OpenRoberta/openroberta-lab/assets/1613069/ecc35b6b-affb-465a-9016-0e1a960476a8)

It is not clear to me whether this error has further consequences, but the desired solution should avoid this error.

**Comment by rbudde** [comment]
solved in commit 1e32d685dc5149399dcbd25522e73a8d4402fbaf

**Comment by bjost2s** [comment]
Unfortunately https://github.com/OpenRoberta/openroberta-lab/commit/1e32d685dc5149399dcbd25522e73a8d4402fbaf does not solve the problem. The error message still appears as soon as you switch the language.

**Comment by rbudde** [comment]
there seem to be a number of problems of this type :-< . Next try

**Comment by TomGruene** [comment]
solved
